image: bradrydzewski/python:2.7-scrapinghub

script:
  - git restore-mtime

publish:
  docker:
    docker_host: $DOCKER_HOST
    image_name: i.scrapinghub.com/portia/$CI_BRANCH
    keep_build: true

cache:
  - /home/ubuntu/.npm
  - /home/ubuntu/.cache
